language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

allow_failures:
  - php: nightly

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - travis_retry composer self-update

script:
  - travis_retry phpunit

# cache vendors
cache:
  directories:
    - vendor
    - $HOME/.composer/cache  
